name: scrum_tools
description: Tools for Scrum
version: 0.0.1
author: Jorge Murcia <jorge@ondesta.es>
environment:
  sdk: '>=1.19.0 <2.0.0'
dependencies:
  angular2: ^2.2.0
  prompt:
dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  start: ^0.2.7
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: [web/daily1.dart, web/daily2.dart]
    $exclude: web/font-awesome-4.7.0
- dart_to_js_script_rewriter
